add_newline = true

[battery]
full_symbol = "ó±Ÿ¢"
charging_symbol = "ó°‚„"
discharging_symbol = "ó°‚ƒ"
format = '[$symbol$percentage]($style) '

[[battery.display]]
threshold = 50
style = "bold #d9bb80"
discharging_symbol = "ó°¾"

[[battery.display]]
threshold = 40
style = "bold #d9bb80"
discharging_symbol = "ó°½"

[[battery.display]]
threshold = 30
style = "bold #d9bb80"
discharging_symbol = "ó°¼"

[[battery.display]]
threshold = 20
style = "bold #e68183"
discharging_symbol = "ó°»"

[[battery.display]]
threshold = 10
style = "bold #e68183"
discharging_symbol = "ó°º"

[character]
success_symbol = "[âœ](bold #a7c080)"
error_symbol = "[âœ—](bold #e68183)"

[cmd_duration]
style = "bold #d9bb80"

[container]
symbol = 'ï†² '
style = 'bold red'
format = '[$symbol]($style) '
disabled = false

[directory]
style = "bold #d9bb80"
truncation_length = 2

[git_branch]
symbol = 'î‚  '
style = "bold #d39bb6"

[git_commit]
commit_hash_length = 4
tag_symbol = 'ï…² '

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = '[ğŸ’ PICKING](bold red)'

[git_metrics]
added_style = 'bold blue'
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '

[git_status]
style = "bold #a7c080"
modified = '[${count}ó°’ ](#d9bb80)'
staged = '[${count}ó±ˆ– ](#83b6af)'
untracked = "[${count}ó°©‹ ](#e68183)"
renamed = '[${count}ó°¬² ](#87c095)'
deleted = '[${count}ó°®˜ ](#e68183)'
ahead = "[${count}ó°©](#a7c080)"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
behind = "â‡£${count}"
stashed = '[${count}ï ](#87c095)'

[hostname]
style = "bold #83b6af"
ssh_only = false
ssh_symbol = "îˆ® "
format = '[$ssh_symbol](bold #83b6af)[$hostname](bold #e68183) '
disabled = false

[localip]
ssh_only = true
format = '@[$localipv4](bold #e68183) '
disabled = false

[os]
format = "[$symbol]($style) "
style = "bold #83b6af"
disabled = false

[os.symbols]
Alpine = "ïŒ€ "
Amazon = "ï‰° "
Android = "îœ "
Arch = "ïŒƒ "
CentOS = "ïŒ„ "
Debian = "ïŒ† "
DragonFly = "ğŸ‰"
Emscripten = "ğŸ”—"
EndeavourOS = "ğŸš€"
Fedora = "ïŒŠ "
FreeBSD = "ïŒŒ "
Garuda = "ğŸ¦…"
Gentoo = "ïŒ "
HardenedBSD = "ğŸ›¡ï¸"
Illumos = "ğŸ¦"
Linux = "îœ’ "
Macos = "ïŒ‚ "
Manjaro = "ïŒ’ "
Mariner = "ğŸŒŠ"
MidnightBSD = "ğŸŒ˜"
Mint = "ïŒ "
NetBSD = "ïŒŒ "
NixOS = "ïŒ“ "
OpenBSD = "ïŒŒ "
openSUSE = "ïŒ” "
OracleLinux = "ğŸ¦´"
Pop = "ğŸ­"
Raspbian = "ïŒ• "
Redhat = "ïŒ– "
RedHatEnterprise = "ïŒ– "
Redox = "ğŸ§ª"
Solus = "â›µ"
SUSE = "ïŒ” "
Ubuntu = "ïŒ› "
Unknown = "îœ’ "
Windows = "ï…º "

[package]
disabled = true

[sudo]
style = "bold #e68183"
symbol = "ï‹ "
disabled = true

[time]
time_format = "%T"
format = "î $time($style) "
style = "bold #a7c080"
disabled = true

[username]
format = "[$user]($style)"
style_user = "bold #87c095"
style_root = 'bold #e68183'
disabled = true
show_always = true

[c]
symbol = 'î±'

[lua]
symbol = 'î ¦'

[python]
symbol = 'îœ¼'

[rlang]
disabled = false
symbol = 'î¢'
format = 'with [$symbol $version](blue bold) '

